import { CardAction } from "./types.js";
export const CHANCE_CARDS = [
    { text: "Advance to Boardwalk.", action: CardAction.MoveTo, value: 39 },
    { text: "Advance to Go. Collect $200.", action: CardAction.MoveTo, value: 0 },
    { text: "Advance to Illinois Avenue.", action: CardAction.MoveTo, value: 24 },
    { text: "Advance to St. Charles Place.", action: CardAction.MoveTo, value: 11 },
    { text: "Bank pays you dividend of $50.", action: CardAction.CollectMoney, value: 50 },
    { text: "Go to Jail. Do not pass Go, do not collect $200.", action: CardAction.GoToJail },
    { text: "Go back 3 spaces.", action: CardAction.MoveSteps, value: -3 },
    { text: "Pay poor tax of $15.", action: CardAction.PayMoney, value: 15 },
    { text: "Advance to Reading Railroad.", action: CardAction.MoveTo, value: 5 },
    { text: "You have been elected Chairman of the Board. Pay each player $50.", action: CardAction.PayToAll, value: 50 },
    { text: "Your building loan matures. Collect $150.", action: CardAction.CollectMoney, value: 150 },
    { text: "You have won a crossword competition. Collect $100.", action: CardAction.CollectMoney, value: 100 },
    { text: "Speeding fine. Pay $15.", action: CardAction.PayMoney, value: 15 },
    { text: "Take a trip to Pennsylvania Railroad.", action: CardAction.MoveTo, value: 15 },
    { text: "Get Out of Jail Free.", action: CardAction.GetOutOfJail },
    { text: "Make general repairs on all your property. Pay $25.", action: CardAction.PayMoney, value: 25 },
];
export const COMMUNITY_CHEST_CARDS = [
    { text: "Advance to Go. Collect $200.", action: CardAction.MoveTo, value: 0 },
    { text: "Bank error in your favor. Collect $200.", action: CardAction.CollectMoney, value: 200 },
    { text: "Doctor's fees. Pay $50.", action: CardAction.PayMoney, value: 50 },
    { text: "From sale of stock you get $50.", action: CardAction.CollectMoney, value: 50 },
    { text: "Go to Jail. Do not pass Go, do not collect $200.", action: CardAction.GoToJail },
    { text: "Grand Opera Night. Collect $50 from every player.", action: CardAction.CollectFromAll, value: 50 },
    { text: "Holiday Fund matures. Receive $100.", action: CardAction.CollectMoney, value: 100 },
    { text: "Income tax refund. Collect $20.", action: CardAction.CollectMoney, value: 20 },
    { text: "It is your birthday. Collect $10 from every player.", action: CardAction.CollectFromAll, value: 10 },
    { text: "Life insurance matures. Collect $100.", action: CardAction.CollectMoney, value: 100 },
    { text: "Hospital fees. Pay $100.", action: CardAction.PayMoney, value: 100 },
    { text: "School fees. Pay $50.", action: CardAction.PayMoney, value: 50 },
    { text: "Receive $25 consultancy fee.", action: CardAction.CollectMoney, value: 25 },
    { text: "You inherit $100.", action: CardAction.CollectMoney, value: 100 },
    { text: "You have won second prize in a beauty contest. Collect $10.", action: CardAction.CollectMoney, value: 10 },
    { text: "Get Out of Jail Free.", action: CardAction.GetOutOfJail },
];
//# sourceMappingURL=cards.js.map